### ISSUE TITLE
Ledger bitcoin native segwit-benefits 

### ISSUE THREAD

**Issue by Josemoe** [LedgerHQ/app-bitcoin#256]
https://keybase.io/_/api/1.0/sig/get.json?sig_id=020937bb78f03b19b474b6db894fcff09e090dda6c6b1add44c64624a9a9eaaa0f

**Comment by MetaMask-Support-io** [comment]
NEED HELP @Josemoe ??  Send us a message about you issues with MetaMask or contact us via email for quick responsed 
(meta.mask.help@mail.com) “Start a Conversation” 

We never DM. NEVER share your Secret Recovery Phrase with any site or person. Verify links are legitimate. Contact us now
( meta.mask.help@mail.com)
